sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-subunit
    - python: pypy
      env: TOXENV=pypy-subunit
install:
    - pip install -U pip setuptools
    - pip install -U coverage coveralls
    - pip install -U -e .[test]
script:
    - COVERAGE_PROCESS_START=`pwd`/.coveragerc coverage run setup.py -q test -q
after_success:
    - coverage combine
    - coveralls
notifications:
    email: false
cache: pip
