sudo: false
language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: pypy3.3-5.5-alpha
      env: TOXENV=pypy3
env:
    - TOXENV=py27
    - TOXENV=py27-subunit
    - TOXENV=pypy
    - TOXENV=pypy-subunit
    - TOXENV=py33
    - TOXENV=py34
install:
    - pip install tox
script:
    - tox
notifications:
    email: false
