environment:

  matrix:
    - python: 27
    - python: 27-x64
    - python: 33
    - python: 33-x64
    - python: 34
    - python: 34-x64
    - python: 35
    - python: 35-x64
    - python: 36
    - python: 36-x64
    - { python: 27, SUBUNIT: 1 }
    - { python: 27-x64, SUBUNIT: 1 }

install:
  - "SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%"
  - pip install -e .[test]
  - ps: if($env:SUBUNIT -eq 1) { pip install python-subunit }

build: false

test_script:
  - python setup.py -q test -q

on_success:
  - echo Build succesful!
